### ISSUE TITLE
[ENHANCEMENT]Using a specific configuration file

### ISSUE THREAD

**Issue by RMTT** [manilarome/the-glorious-dotfiles#157]
I think that if using a specific file for configuration is advantage for install and update this project.
There is two popular configuration format i know: toml and yaml,if using yaml,[this library](https://github.com/gvvaughan/lyaml) seems very useful and updated recently, but for the toml, i can just find [this library](https://github.com/jonstoler/lua-toml), have stopped for 3 years.
For example,configure the secrets:
```yaml
email:
  address: ''
  app_password: ''
  imap_server: ''
weather:
  key: ''
  city_id: ""
```
and tags:
```yaml
tags:
  - 
    icon: ...
    default_app: 'code-oss'
    type: 'xx'
  -
    icon: ..
    default_app: 'chrome-stable'
    ...
```
even startup program:
```yaml
start_up:
  - "mpd"
  - "redshift"
  ...
```
